apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: appwrite-worker-audits
  name: appwrite-worker-audits
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: appwrite-worker-audits
  template:
    metadata:
      labels:
        io.kompose.network/appwrite: "true"
        io.kompose.service: appwrite-worker-audits
    spec:
      containers:
      - command:
        - worker-audits
        image: appwrite/appwrite:0.7.2
        name: appwrite-worker-audits
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: appwrite-worker-certificates
  name: appwrite-worker-certificates
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: appwrite-worker-certificate
  template:
    metadata:
      labels:
        io.kompose.network/appwrite: "true"
        io.kompose.service: appwrite-worker-certificates
    spec:
      containers:
      - command:
        - worker-certificates
        image: appwrite/appwrite:0.7.2
        name: appwrite-worker-certificates
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: appwrite-worker-deletes
  name: appwrite-worker-deletes
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: appwrite-worker-deletes
  template:
    metadata:
      labels:
        io.kompose.network/appwrite: "true"
        io.kompose.service: appwrite-worker-deletes
    spec:
      containers:
      - command:
        - worker-deletes
        image: appwrite/appwrite:0.7.2
        name: appwrite-worker-deletes
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: appwrite-worker-functions
  name: appwrite-worker-functions
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: appwrite-worker-functions
  template:
    metadata:
      labels:
        io.kompose.network/appwrite: "true"
        io.kompose.service: appwrite-worker-functions
    spec:
      containers:
      - command:
        - worker-functions
        image: appwrite/appwrite:0.7.2
        name: appwrite-worker-functions
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: appwrite-worker-mails
  name: appwrite-worker-mails
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: appwrite-worker-mails
  template:
    metadata:
      labels:
        io.kompose.network/appwrite: "true"
        io.kompose.service: appwrite-worker-mails
    spec:
      containers:
      - command:
        - worker-mails
        image: appwrite/appwrite:0.7.2
        name: appwrite-worker-mails
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: appwrite-schedule
  name: appwrite-schedule
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: appwrite-schedule
  template:
    metadata:
      labels:
        io.kompose.network/appwrite: "true"
        io.kompose.service: appwrite-schedule
    spec:
      containers:
      - command:
        - schedule
        image: appwrite/appwrite:0.7.2
        name: appwrite-schedule
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: appwrite-worker-tasks
  name: appwrite-worker-tasks
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: appwrite-worker-tasks
  template:
    metadata:
      labels:
        io.kompose.network/appwrite: "true"
        io.kompose.service: appwrite-worker-tasks
    spec:
      containers:
      - command:
        - worker-tasks
        image: appwrite/appwrite:0.7.2
        name: appwrite-worker-tasks
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: appwrite-worker-usage
  name: appwrite-worker-usage
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: appwrite-worker-usage
  template:
    metadata:
      labels:
        io.kompose.network/appwrite: "true"
        io.kompose.service: appwrite-worker-usage
    spec:
      containers:
      - command:
        - worker-usage
        image: appwrite/appwrite:0.7.2
        name: appwrite-worker-usage
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: appwrite-worker-webhooks
  name: appwrite-worker-webhooks
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: appwrite-worker-webhooks
  template:
    metadata:
      labels:
        io.kompose.network/appwrite: "true"
        io.kompose.service: appwrite-worker-webhooks
    spec:
      containers:
      - command:
        - worker-webhooks
        image: appwrite/appwrite:0.7.2
        name: appwrite-worker-webhooks
      restartPolicy: Always