apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mariadb
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/appwrite: "true"
        io.kompose.service: mariadb
    spec:
      containers:
      - args:
        - mysqld
        - --innodb-flush-method=fsync
        env:
        - name: MYSQL_DATABASE
          value: "appwrite"
        - name: MYSQL_USER
          value: "user"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "appwrite-mariadb"
              key: "mysql-password"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "appwrite-mariadb"
              key: "mysql-root-password"
        image: appwrite/mariadb:1.2.0
        name: appwrite-mariadb
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: appwrite-mariadb
      restartPolicy: Always
      volumes:
      - name: appwrite-mariadb
        persistentVolumeClaim:
          claimName: appwrite-mariadb
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mariadb
  name: mariadb
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    io.kompose.service: mariadb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mariadb
  name: appwrite-mariadb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi