apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/appwrite: "true"
        io.kompose.service: redis
    spec:
      containers:
      - image: redis:6.0
        name: appwrite-redis
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /data
          name: appwrite-redis
      restartPolicy: Always
      volumes:
      - name: appwrite-redis
        persistentVolumeClaim:
          claimName: appwrite-redis
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: redis
  name: redis
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    io.kompose.service: redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: appwrite-redis
  name: appwrite-redis
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi