#TODO: you may wish to also add a secret for _APP_OPENSSL_KEY_V1 too
apiVersion: v1
kind: Secret
metadata:
  name: appwrite-mariadb
type: Opaque
data:
  #TODO: insert your base64 encoded passwords here. Be careful not to include a newline when base64 encoding
  "mysql-password": "<base64 encoded password here>" 
  "mysql-root-password": "<base64 encoded password here>"
---
apiVersion: v1
kind: Secret
metadata:
  name: appwrite-mail
type: Opaque
data:
  #TODO: insert your base64 encoded smtp password here
  "smtp-password": "<base64 encoded password here>"